POST http://localhost:3030/events
Content-Type: application/json

{
  "title": "Evento 4",
  "details": "Evento de teste",
  "maximumAttendees": 1
}


###

POST http://localhost:3030/events/b69a2566-a0fa-4154-a86d-811e6dea926f/attendees
Content-Type: application/json

{
  "name": "Igor",
  "email": "igo2r@gmail.com"
}

###

GET http://localhost:3030/events/b69a2566-a0fa-4154-a86d-811e6dea926f

###

GET http://localhost:3030/attendees/1/badge
